
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Basket {
			/**
			* Session Address Book
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#161) 
			*/
			sessionAddressBook: string | null;

		}
		interface BonusDiscountLineItem {
			/**
			* Bonus Product Line Item UUID

				This represents the UUID of the product line item that holds the qualifying product.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#185) 
			*/
			bonusProductLineItemUUID: string | null;

		}
		interface Category {
			/**
			* Page ID

				Specify the Page Designer page ID.
			* @group Presentation - Presentation Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#387) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#508)
			*/
			DittoPDPageID: string | null;

			/**
			* Alternative URL

				Renders an alternative URL in main navigation. Uses Commerce Cloud content url notation. For example: $url('Account-Show')$ or normal URL http://xchange.demandware.com
			* @group ExternalSearch - Search Engine Optimization Support
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#396) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#494)
			*/
			alternativeUrl: MarkupText | null;

			/**
			* Category Banner ID

				Used to define the content asset used to populate a grid page banner for a category. This value is applied to all sub-category navigation (cascading) if no specific catBannerID has been defined for  a sub-category.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#406) 
			*/
			catBannerID: string | null;

			/**
			* Custom CSS File

				Use this attribute to apply custom styles for this category.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#415) 
			*/
			customCSSFile: MediaFile | null;

			/**
			* Enable Compare

				Used to define if/when the Compare feature is to be visualized in the storefront based on navigation. If enableCompare = FALSE, no Compare checkboxes will be displayed in the grid view. If enableCompare = TRUE, the category (and its children) will support the Compare feature.
			* @group Presentation - Presentation Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#423) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#505)
			*/
			enableCompare: boolean | null;

			/**
			* Header Menu Banner
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#430) 
			*/
			headerMenuBanner: MarkupText | null;

			/**
			* Header Menu Orientation

				Which way to orient the menu and optional header menu HTML. Vertical will list all in one line. Horizontal will list in columns.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#437) 
			*/
			headerMenuOrientation: EnumValue<'Horizontal' | 'Vertical' | null> 

			/**
			* Show in Menu Navigation

				Used to indicate that a category (such as Mens -> Footwear -> Boots) will display in the roll-over navigation. A sub-category only shows if also the parent category is marked as showInMenu. Up to three category levels are shown in roll-over navigation.
			* @group Presentation - Presentation Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#455) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#504)
			*/
			showInMenu: boolean | null;

			/**
			* Size Chart

				Used to define the content asset ID of the Size Chart that is appropriate for products whose PRIMARY category is the associated category (and its children). Whenever a product detail page (or quick view) is rendered, the Size Chart link is populated based on the value of this attribute for the products primary categorization. If not defined, NO size chart link is displayed.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#462) 
			*/
			sizeChartID: string | null;

			/**
			* Slot Banner HTML
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#471) 
			*/
			slotBannerHtml: MarkupText | null;

			/**
			* Category Landing Slot Image

				Image used on either the top or bottom slot on the category landing pages.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#478) 
			*/
			slotBannerImage: MediaFile | null;

		}
		interface Content {
			/**
			* Body
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#648) 
			*/
			body: MarkupText | null;

		}
		interface Order {
			/**
			* SOM Source Code
			* @group SOM - Salesforce Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1524) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1571)
			*/
			somSourceCode: string | null;

			/**
			* Salesforce Sync Response Text

				Stores the response from last processed Service Cloud Order record synchronization attempt.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1531) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1576)
			*/
			sscSyncResponseText: ReadonlyArray<string> 

			/**
			* Salesforce Service Cloud SyncStatus

				Describes the Salesforce Service Cloud Order Synchronization Status.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1538) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1575)
			*/
			sscSyncStatus: EnumValue<'created' | 'exported' | 'updated' | null> 

			/**
			* Salesforce Service Cloud Order ID

				Represents the Salesforce Service Cloud OrderId
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1559) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1577)
			*/
			sscid: string | null;

		}
		interface OrganizationPreferences {
			/**
			* b2cDemoMetadata
			* @group b2cDemoMetadata - My Project Meta
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1786) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1828)
			*/
			b2cDemoMetadata: string | null;

			/**
			* b2c-tools Metadata Version
			* @group b2cDemoMetadata - My Project Meta
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1793) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1827)
			*/
			b2cDemoMetadataVersion: number | null;

			/**
			* b2c-tools Metadata Version
			* @group b2cToolkit - b2c-tools
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1799) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1821)
			*/
			b2cToolkitDataVersion: number | null;

			/**
			* b2c-tools Applied Migrations
			* @group b2cToolkit - b2c-tools
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1805) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1822)
			*/
			b2cToolkitMigrations: string | null;

			/**
			* b2c-tools Bootstrapped Client IDs
			* @group b2cToolkit - b2c-tools
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1811) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1823)
			*/
			b2cToolsBootstrappedClientIDs: string | null;

		}
		interface PaymentTransaction {
			/**
			* eFunds Transaction History
			* @group Custom - Custom
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1910) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#1920)
			*/
			eFundsTransactionHistory: ReadonlyArray<string> 

		}
		interface Product {
			/**
			* Activity
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2274) 
			*/
			activity: ReadonlyArray<EnumValue<'Hiking' | 'Climbing' | 'Cycling' | 'Training' | 'City' | 'Snowboarding' | 'Skiing' | 'Running' | 'Bike Commuting' | 'Bikepacking' | 'Bike Touring' | 'Cyclocross' | 'Fitness' | 'Mountain Biking' | 'Recreational Cycling' | 'Road Cycling' | 'Urban Cycling' | 'Walking'>> 

			/**
			* Altimeter
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2445) 
			*/
			altimeter: ReadonlyArray<EnumValue<'Satellite-based' | 'Pressure-based' | 'No'>> 

			/**
			* Apparel Features
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2471) 
			*/
			apparelFeatures: ReadonlyArray<EnumValue<'Waterproof' | 'Wind Protection' | 'Lightweight' | 'Thumbholes' | 'Hooded' | 'Recycled Content' | 'Soft' | 'Breathable' | 'Vibram' | 'Stretch' | 'Medium Impact' | 'High Impact' | 'Water Resistant' | 'Durable Water Repellent' | 'Insulated' | 'Media Compatible' | 'Packable/Stowable' | 'UPF' | 'Reflective' | 'Women-Specific Fit' | 'Hydration Compatible' | 'Reversible' | 'Non-Hooded' | 'Zip/Snap-in Compatible' | 'Goose-down'>> 

			/**
			* Available for In Store Pickup

				Signals if there are inventory lists for brick-and-mortar stores associated with this product.
			* @group ChannelIntegration - Channel Integration Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2699) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4402)
			*/
			availableForInStorePickup: boolean | null;

			/**
			* Battery Life
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2710) 
			*/
			batteryLife: string | null;

			/**
			* Battery Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2722) 
			*/
			batteryType: string | null;

			/**
			* Bulb Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2734) 
			*/
			bulbType: string | null;

			/**
			* Category
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2746) 
			*/
			['category-1']: string | null;

			/**
			* Sub-Category
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2758) 
			*/
			['category-2']: string | null;

			/**
			* Sub-Sub-Category
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2770) 
			*/
			['category-3']: string | null;

			/**
			* Color

				Product color used for variation attribute
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2782) 
			*/
			color: string | null;

			/**
			* Computer Features
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2802) 
			*/
			computerFeatures: ReadonlyArray<EnumValue<'GPS Tracking' | 'Current Speed' | 'Maximum Speed' | 'Average Speed' | 'Speed Comparator' | 'Odometer' | 'Trip Distance' | 'Auto Start/Stop' | 'Stopwatch' | 'Clock' | 'Alarm' | 'Lap Time' | 'Cadence' | 'Dual Bike Memory'>> 

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2872) 
			*/
			consoleWarranty: string | null;

			/**
			* Count
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2884) 
			*/
			count: string | null;

			/**
			* Custom CSS File

				Use this attribute to apply custom styles for this product.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2896) 
			*/
			customCSSFile: MediaFile | null;

			/**
			* Digital Camera Features
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#2908) 
			*/
			digitalCameraFeatures: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090' | '0100' | '0110' | '0120' | '0130' | '0140' | '0150' | '0160' | '0170' | '0180' | '0190' | '0200' | '0210' | '0220' | '0230' | '0240' | '0250' | '0260' | '0270' | '0280'>> 

			/**
			* Digital Camera Pixels
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3034) 
			*/
			digitalCameraPixels: string | null;

			/**
			* Digital Camera Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3046) 
			*/
			digitalCameraType: string | null;

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3058) 
			*/
			digitalCameraWarranty: string | null;

			/**
			* Depth
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3070) 
			*/
			dimDepth: string | null;

			/**
			* Height
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3082) 
			*/
			dimHeight: string | null;

			/**
			* Weight
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3094) 
			*/
			dimWeight: string | null;

			/**
			* Width
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3106) 
			*/
			dimWidth: string | null;

			/**
			* Dimensions
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3118) 
			*/
			dimensions: string | null;

			/**
			* Display Size
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3130) 
			*/
			displaySize: string | null;

			/**
			* Fabric Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3142) 
			*/
			fabricType: string | null;

			/**
			* Flavor
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3154) 
			*/
			flavor: EnumValue<'Mocha' | 'French Roast' | 'Chai' | 'Green Tea' | 'Tart Cherry' | 'Cranberry' | 'Blueberry' | 'Mint Chocolate' | null> 

			/**
			* Frame Material
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3239) 
			*/
			frameMaterial: string | null;

			/**
			* Genre
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3251) 
			*/
			gameGenre: ReadonlyArray<EnumValue<'Action' | 'Educational' | 'Kids' | 'Racing' | 'Role-Playing' | 'Sports' | 'Strategy'>> 

			/**
			* Game Rating
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3293) 
			*/
			gameRating: string | null;

			/**
			* Gaming System
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3305) 
			*/
			gameSystemType: string | null;

			/**
			* Gear Features
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3317) 
			*/
			gearFeatures: ReadonlyArray<EnumValue<'Internal Organization' | 'Up to 15" Laptop Compatible' | '17" Laptop Compatible' | 'Tablet Sleeve' | 'Water Bottle' | 'Roll top' | 'Emergency whistle' | 'Bottle opener' | 'Helmet Holder' | 'Hip Belt Pockets' | 'Internal Hydration sleeve' | 'Lay flat' | 'Ski Carrier' | 'Tool Keeper/Loop'>> 

			/**
			* GPS Features
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3442) 
			*/
			gpsFeatures: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090' | '0100' | '0110' | '0120' | '0130' | '0140' | '0150' | '0160' | '0170' | '0180' | '0190' | '0200' | '0210' | '0230'>> 

			/**
			* GPS Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3544) 
			*/
			gpsType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040'>> 

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3574) 
			*/
			gpsWarranty: string | null;

			/**
			* Helmet Circumference
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3586) 
			*/
			helmetCircumference: ReadonlyArray<string> 

			/**
			* Helmet Construction
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3597) 
			*/
			helmetConstruction: string | null;

			/**
			* Helmet Style
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3609) 
			*/
			helmetStyle: string | null;

			/**
			* Image Aspect Ratio
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3621) 
			*/
			imageAspectRatio: string | null;

			/**
			* Bulk Order Master

				Enabling Bulk Order Master allows the merchant to purchase all variations of a master from the same PDP and add to cart
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3633) 
			*/
			isBulkOrderMaster: boolean | null;

			/**
			* New Arrival?
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3644) 
			*/
			isNew: boolean | null;

			/**
			* New Arrival?

				This indiciates if the product is a new arrival.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3654) 
			*/
			isNewtest: boolean | null;

			/**
			* On sale?

				This is the help text. It is used for sorting rules.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3665) 
			*/
			isSale: boolean | null;

			/**
			* Length
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3676) 
			*/
			length: string | null;

			/**
			* Material
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3688) 
			*/
			material: string | null;

			/**
			* Media Format

				Media Format
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3700) 
			*/
			mediaFormat: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090' | '0100'>> 

			/**
			* Memory Size

				Memory Size
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3755) 
			*/
			memorySize: string | null;

			/**
			* Memory Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3768) 
			*/
			memoryType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030' | '0040' | '0050' | '0060' | '0070' | '0080' | '0090'>> 

			/**
			* Music Storage
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3818) 
			*/
			musicStorage: string | null;

			/**
			* nonRMA
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3830) 
			*/
			nonRMA: boolean | null;

			/**
			* Number of Bikes
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3840) 
			*/
			numberBikes: string | null;

			/**
			* Number of Bulbs
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3852) 
			*/
			numberBulbs: string | null;

			/**
			* Number of Doors
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3864) 
			*/
			numberDoors: string | null;

			/**
			* Number of Gears
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3876) 
			*/
			numberGears: string | null;

			/**
			* Features
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3888) 
			*/
			nutritionFeatures: ReadonlyArray<EnumValue<'vegan' | 'paleo' | 'hi-protein' | 'pre' | 'during' | 'post'>> 

			/**
			* Optical Zoom
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3956) 
			*/
			opticalZoom: string | null;

			/**
			* Portable Audio Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3968) 
			*/
			portableAudioType: ReadonlyArray<EnumValue<'0010' | '0020' | '0030'>> 

			/**
			* Refinement Color
			* @group Presentation - Presentation Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#3994) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4371)
			*/
			refinementColor: EnumValue<'black' | 'blue' | 'green' | 'red' | 'orange' | 'pink' | 'purple' | 'white' | 'yellow' | 'grey' | 'beige' | 'miscellaneous' | 'brown' | 'navy' | null> 

			/**
			* Resolution
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4070) 
			*/
			resolution: string | null;

			/**
			* Size

				This attribute is used for all footwear, apparel and accessory sizing for men, women and kids products.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4082) 
			*/
			size: string | null;

			/**
			* Sleeping Capacity
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4100) 
			*/
			sleepingCapacity: number | null;

			/**
			* Specifications
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4111) 
			*/
			specifications: MarkupText | null;

			/**
			* Sq Ft
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4122) 
			*/
			sqft: number | null;

			/**
			* Square Footage
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4133) 
			*/
			squareFootage: number | null;

			/**
			* Style Number
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4144) 
			*/
			styleNumber: string | null;

			/**
			* Sustainability
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4157) 
			*/
			sustainability: string | null;

			/**
			* Description
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4169) 
			*/
			tabDescription: MarkupText | null;

			/**
			* Details
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4180) 
			*/
			tabDetails: MarkupText | null;

			/**
			* Tire Width
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4191) 
			*/
			tireWidth: string | null;

			/**
			* Trail Weight
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4203) 
			*/
			trailWeight: string | null;

			/**
			* TV Signal Format
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4215) 
			*/
			tvSignalFormat: string | null;

			/**
			* Size
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4227) 
			*/
			tvSize: string | null;

			/**
			* TV Type
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4239) 
			*/
			tvType: EnumValue<'0010' | '0020' | '0030' | '0040' | null> 

			/**
			* Extended Warranty
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4268) 
			*/
			tvWarranty: string | null;

			/**
			* Video Storage
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4280) 
			*/
			videoStorage: string | null;

			/**
			* Volume
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4292) 
			*/
			volume: string | null;

			/**
			* Waist

				Attribute used for apparel waist sizing.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4304) 
			*/
			waist: string | null;

			/**
			* Weight
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4317) 
			*/
			weight: ReadonlyArray<string> 

			/**
			* Wheel Size
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4328) 
			*/
			wheelSize: string | null;

			/**
			* Width

				This attribute is used for shoe widths for mens, womens and kids.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4340) 
			*/
			width: string | null;

		}
		interface ProductLineItem {
			/**
			* Bonus Product Line Item UUID

				This represents the UUID of the product line item that holds the qualifying product.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4576) 
			*/
			bonusProductLineItemUUID: string | null;

			/**
			* From Store ID

				Links the store to the product line item for grouping shipments in the checkout process.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4584) 
			*/
			fromStoreId: string | null;

			/**
			* pre order uuid

				this custom attribute captures the original product line item uuid before it is part of an placed order
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4592) 
			*/
			preOrderUUID: string | null;

			/**
			* SOM Level 1 Category
			* @group SOM - Salesforce Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4600) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4625)
			*/
			somL1Category: string | null;

			/**
			* SOM Level 2 Category
			* @group SOM - Salesforce Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4607) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4626)
			*/
			somL2Category: string | null;

			/**
			* SOM Level 3 Category
			* @group SOM - Salesforce Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4614) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4627)
			*/
			somL3Category: string | null;

		}
		interface Profile {
			/**
			* Terms
			* @group Paymentterms - Payment Terms
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4828) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4927)
			*/
			Terms: ReadonlyArray<EnumValue<'Net 30' | 'Net 60' | 'Net 90' | 'Purchase Order'>> 

			/**
			* Salesforce Sync Response Text

				Stores the response from last processed Service Cloud Customer record synchronization attempt.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4853) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4923)
			*/
			sscSyncResponseText: ReadonlyArray<string> 

			/**
			* Salesforce Service Cloud SyncStatus

				Describes the Salesforce Service Cloud Customer Record Synchronization Status.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4860) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4920)
			*/
			sscSyncStatus: EnumValue<'exported' | 'created' | 'updated' | null> 

			/**
			* Salesforce Service Cloud Contact ID

				Represents the Salesforce Service Cloud ContactId found on a given PersonAccount.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4881) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4922)
			*/
			ssccid: string | null;

			/**
			* Salesforce Service Cloud Account ID

				Represents the Salesforce Service Cloud AccountId found on a given PersonAccount.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4889) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#4921)
			*/
			sscid: string | null;

		}
		interface ServiceCredential {
			/**
			* BM Auth Access Key
			* @group Additional - Additional
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5263) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5321)
			*/
			bmAuthAccessKey: string | null;

			/**
			* BM Auth User
			* @group Additional - Additional
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5269) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5322)
			*/
			bmAuthUser: string | null;

			/**
			* Consumer Key

				Represents the Consumer Key associated to the CommerceCloudConnect Connected App in Service Cloud.
			* @group serviceCloudConnectorAttributes - Service Cloud Connector Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5276) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5316)
			*/
			clientid: string | null;

			/**
			* Consumer Secret

				Represents the Consumer Secret associated to the CommerceCloudConnect Connected App in Service Cloud.
			* @group serviceCloudConnectorAttributes - Service Cloud Connector Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5284) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5317)
			*/
			clientsecret: string | null;

			/**
			* Consumer Key

				Represents the Consumer Key associated to the Connected App in LOM.
			* @group lomConnectionAttributes - LOM Connection Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5291) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5310)
			*/
			lomClientid: string | null;

			/**
			* Consumer Secret

				Represents the Consumer Secret associated to the Connected App in LOM.
			* @group lomConnectionAttributes - LOM Connection Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5299) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5311)
			*/
			lomClientsecret: string | null;

		}
		interface Shipment {
			/**
			* Pickup Store ID

				Used to map the shipment to a  brick and mortar store.
			* @group storepickup - Store Pickup Information
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5375) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5404)
			*/
			fromStoreId: string | null;

			/**
			* When this attribute equals 'instore', the checkout flow will assign the shipping method (005) which has a no shipping charge.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5384) 
			*/
			shipmentType: string | null;

			/**
			* Store Pickup Message

				This is text used by the end user when sending a message to the brick and mortar store about the shipment.  This is reflected in the order export.
			* @group storepickup - Store Pickup Information
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5391) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5405)
			*/
			storePickupMessage: string | null;

		}
		interface ShippingMethod {
			/**
			* Estimated Arrival Time

				Estimated days until delivery
			* @group shippingMethodAttr - Shipping Method Attributes
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5443) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5466)
			*/
			estimatedArrivalTime: string | null;

			/**
			* Store Pickup Enabled
			* @group storePickUp - Store Pick Up
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5452) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5462)
			*/
			storePickupEnabled: boolean | null;

		}
		interface SitePreferences {
			/**
			* Embedded Service Code Snippets

				https://help.salesforce.com/articleView?id=snapins_chat_get_code.htm&type=5
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5552) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5995)
			*/
			DittoEmbeddedServiceCodeSnippet: string | null;

			/**
			* Google Tag Manager Container
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5559) 
			*/
			DittoGoogleTagManagerContainer: string | null;

			/**
			* New Product Timeframe

				The number of days since the creation date to identify a product as 'new'.
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5566) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5994)
			*/
			DittoNewProductTimeframe: number | null;

			/**
			* Page Designer Home Page ID
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5574) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5993)
			*/
			DittoPDHomePageID: string | null;

			/**
			* Google Tag Manager Body Snippet

				Paste the GTM body snippet here
			* @group GTM - Google Tag Manager
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5581) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6013)
			*/
			GTMBodySnippet: string | null;

			/**
			* Google Tag Manager Head Snippet

				Paste the GTM head snippet here
			* @group GTM - Google Tag Manager
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5588) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6012)
			*/
			GTMHeadSnippet: string | null;

			/**
			* GoogleVerificationTag - Content Attribute
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5595) 
			*/
			GoogleVerificationTag: string | null;

			/**
			* SC OOBO Guest Checkout CustomerId

				CustomerId used to facilitate the SFSC OOBO for non-registered users.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5602) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5973)
			*/
			OOBOGuestCustomerId: string | null;

			/**
			* No. of Objects in Bulk-Create Call

				Represents the total number of customers or orders to process during the execution of a Service Cloud Connector synchronization jobs.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5610) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5972)
			*/
			bulkCallThreshold: number | null;

			/**
			* Check TLS

				When true, this causes a TLS check to take place based on whether or not a cookie ('dw_TLSWarning') has been set on the browser
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5619) 
			*/
			checkTLS: boolean | null;

			/**
			* Default Country Code

				Default country code for store searches
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5627) 
			*/
			countryCode: EnumValue<'US' | 'CA' | null> 

			/**
			* Customer Service Email
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5644) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5978)
			*/
			customerServiceEmail: string | null;

			/**
			* Enable SOM Self Service Plugin
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5653) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5996)
			*/
			dittoSomSelfServiceEnabled: boolean | null;

			/**
			* Enable MultiShipping

				The attribute is used to enable/disable Multi-Shipment Checkout for each site via BM.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5660) 
			*/
			enableMultiShipping: boolean | null;

			/**
			* Default List Price Book ID
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5668) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5977)
			*/
			listPriceDefault: string | null;

			/**
			* Allow Order Cancellation Statuses

				LOM Order statuses where an order will be cancellable
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5676) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6021)
			*/
			['lom.allowOrderCancellationStatuses']: ReadonlyArray<string> 

			/**
			* Allow Order Return Statuses

				LOM Order statuses where an order will be returnable
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5683) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6022)
			*/
			['lom.allowOrderReturnStatuses']: ReadonlyArray<string> 

			/**
			* Auth Token Custom Object Id

				Custom Object used to store/cache SF Auth Tokens.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5690) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6018)
			*/
			['lom.authTokenCustomObjectId']: string | null;

			/**
			* Activate LOM integration

				Flag used to enable or disable integration with Salesforce OMS.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5700) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6017)
			*/
			['lom.isActive']: boolean | null;

			/**
			* Earliest Year for Order Search

				Earliest year used to create date filters in Order History.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5707) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6019)
			*/
			['lom.ordersearch.earlierYear']: number | null;

			/**
			* Order Status Mappings

				Allows the mapping of SF LOM status names into SF CC status names.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5715) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6020)
			*/
			['lom.statusMappings']: ReadonlyArray<string> 

			/**
			* google map api key
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5722) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5980)
			*/
			mapAPI: string | null;

			/**
			* Marketing Cloud collect.js URL

				Marketing Cloud collect.js URL. The string MCMID must exist in the URL, for the marketing cloud MID to be inserted into the URL.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5729) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6004)
			*/
			mcCollectJsUrl: string | null;

			/**
			* Marketing Cloud Default Mailing Lists

				Default Marketing Cloud mailing lists to assign when customer subscribes. Please provide the numeric "List ID" value.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5739) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6006)
			*/
			mcDefaultMailingLists: ReadonlyArray<number> 

			/**
			* Marketing Cloud Enable Analytics

				Select Yes to enable Marketing Cloud Analytics tracking. Requires Member ID to be set.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5746) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6000)
			*/
			mcEnableAnalytics: boolean | null;

			/**
			* Marketing Cloud Enable Mailing List Hooks

				Select Yes to enable Marketing Cloud mailing list functionality.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5754) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6005)
			*/
			mcEnableMailingLists: boolean | null;

			/**
			* Marketing Cloud Include Tracking Link

				Select Yes to output Marketing Cloud Analytics tracking link into the storefront. Requires Member ID to be set.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5762) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6003)
			*/
			mcIncludeTrackingLink: boolean | null;

			/**
			* Marketing Cloud Member ID

				Marketing Cloud Business Unit Member ID aka MID
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5770) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6001)
			*/
			mcMID: string | null;

			/**
			* Parent Marketing Cloud Member ID

				Optional parent Marketing Cloud Business Unit Member ID.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5779) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6002)
			*/
			mcMIDParent: string | null;

			/**
			* Marketing Cloud Mailing Lists Whitelist

				Whitelist of Marketing Cloud mailing lists. If left empty, all lists are listed for customer. Please provide the numeric "List ID" value.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5788) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6007)
			*/
			mcMailingListsWhitelist: ReadonlyArray<number> 

			/**
			* Marketing Cloud Allow Unsubscribing from Lists over Deletion

				This flag will allow the Marketing Cloud cartridge to Unsubscribe users from assigned mailing lists, thus updating the subscriber's status from "Active" to "Unsubscribed".
This will be used in place of fully deleting the record from the list.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5795) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6008)
			*/
			mcUnsubscribeAllowed: boolean | null;

			/**
			* Rate Limiter Threshold

				This number indicates the number of times failures for Logins, GiftCert Balances, and Order Tracking requests will be allowed before displaying a CAPTCHA-style pop-up rate limiter
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5804) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5979)
			*/
			rateLimiterThreshold: number | null;

			/**
			* SFRA - Enable Apple Pay

				Enables the Apple Pay plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_applepay must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5813) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5988)
			*/
			sfraEnableOverlayApplePay: boolean | null;

			/**
			* SFRA - Enable Data Download

				Enables the Data Download plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_datadownload must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5821) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5985)
			*/
			sfraEnableOverlayDataDownload: boolean | null;

			/**
			* SFRA - Enable Gift Registry

				Enables the Gift Registry plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_giftregistry must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5829) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5987)
			*/
			sfraEnableOverlayGiftRegistry: boolean | null;

			/**
			* SFRA - Enable In Store Pickup

				Enables the In Store Pickup Plugin in the SFRA Unified Feature Cartridge. Note: The plugin_instorepickup must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5837) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5984)
			*/
			sfraEnableOverlayInStorePickup: boolean | null;

			/**
			* SFRA - Enable Product Compare

				Enables the Product Compare plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_productcompare must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5845) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5989)
			*/
			sfraEnableOverlayProductCompare: boolean | null;

			/**
			* SFRA - Enable Wishlist

				Enables the Wishlist plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_wishlists must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5853) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5986)
			*/
			sfraEnableOverlayWishlist: boolean | null;

			/**
			* Shipped Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5861) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6033)
			*/
			somStatusCancelledLabel: string | null;

			/**
			* In Progress Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5869) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6031)
			*/
			somStatusInProgressLabel: string | null;

			/**
			* Ordered Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5877) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6030)
			*/
			somStatusOrderedLabel: string | null;

			/**
			* Returned Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5885) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6034)
			*/
			somStatusReturnedLabel: string | null;

			/**
			* Shipped Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5893) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6032)
			*/
			somStatusShippedLabel: string | null;

			/**
			* Is Async Mode Enabled?

				When enabled, synchronization occurs in real-time with the jobs serving as a fallback (jobs then only process failed real-time synchronizations).  Otherwise, all cross-cloud synchronization will be driven by the SCC jobs.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5901) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5968)
			*/
			sscIsAsync: boolean | null;

			/**
			* Is Enabled?

				Global enablement flag for the SFCC / SFSC integration; when false, no integration messages are shared with Service Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5909) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5967)
			*/
			sscIsEnabled: boolean | null;

			/**
			* Salesforce Connected App Password

				Salesforce Connected App Password
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5917) 
			*/
			sscPassword: string | null;

			/**
			* Salesforce Connected App Username

				Salesforce Connected App Username
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5925) 
			*/
			sscUsername: string | null;

			/**
			* Synchronize Cases?

				When enabled, cases created by customers are synchronized with Service Cloud when created / updated in Commerce Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5933) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5971)
			*/
			syncCasesEnabled: boolean | null;

			/**
			* Synchronize Customers?

				When enabled, customer profiles are synchronized with Service Cloud when created / updated in Commerce Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5941) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5969)
			*/
			syncCustomersEnabled: boolean | null;

			/**
			* Synchronize Orders?

				When enabled, orders placed by customers are synchronized with Service Cloud when created / updated in Commerce Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5949) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5970)
			*/
			syncOrdersEnabled: boolean | null;

			/**
			* Test Preference For demo 2
			* @group TestDemoPrefs - Test Demo Prefs
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5957) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6026)
			*/
			testPreferenceForDemo2: string | null;

		}
		interface Store {
			/**
			* Country Code Value

				Country Code Value - for the form values
			* @group Address - Address
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6177) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6213)
			*/
			countryCodeValue: string | null;

			/**
			* Store Inventory List ID

				Store Inventory List ID
			* @group Inventory - Inventory
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6186) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6231)
			*/
			inventoryListId: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Embedded Service Code Snippets

				https://help.salesforce.com/articleView?id=snapins_chat_get_code.htm&type=5
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5552) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5995)
			*/
			(name: 'DittoEmbeddedServiceCodeSnippet'): string | null;
			
			/**
			* Google Tag Manager Container
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5559) 
			*/
			(name: 'DittoGoogleTagManagerContainer'): string | null;
			
			/**
			* New Product Timeframe

				The number of days since the creation date to identify a product as 'new'.
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5566) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5994)
			*/
			(name: 'DittoNewProductTimeframe'): number | null;
			
			/**
			* Page Designer Home Page ID
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5574) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5993)
			*/
			(name: 'DittoPDHomePageID'): string | null;
			
			/**
			* Google Tag Manager Body Snippet

				Paste the GTM body snippet here
			* @group GTM - Google Tag Manager
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5581) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6013)
			*/
			(name: 'GTMBodySnippet'): string | null;
			
			/**
			* Google Tag Manager Head Snippet

				Paste the GTM head snippet here
			* @group GTM - Google Tag Manager
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5588) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6012)
			*/
			(name: 'GTMHeadSnippet'): string | null;
			
			/**
			* GoogleVerificationTag - Content Attribute
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5595) 
			*/
			(name: 'GoogleVerificationTag'): string | null;
			
			/**
			* SC OOBO Guest Checkout CustomerId

				CustomerId used to facilitate the SFSC OOBO for non-registered users.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5602) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5973)
			*/
			(name: 'OOBOGuestCustomerId'): string | null;
			
			/**
			* No. of Objects in Bulk-Create Call

				Represents the total number of customers or orders to process during the execution of a Service Cloud Connector synchronization jobs.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5610) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5972)
			*/
			(name: 'bulkCallThreshold'): number | null;
			
			/**
			* Check TLS

				When true, this causes a TLS check to take place based on whether or not a cookie ('dw_TLSWarning') has been set on the browser
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5619) 
			*/
			(name: 'checkTLS'): boolean | null;
			
			/**
			* Default Country Code

				Default country code for store searches
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5627) 
			*/
			(name: 'countryCode'): EnumValue<'US' | 'CA' | null> 
			
			/**
			* Customer Service Email
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5644) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5978)
			*/
			(name: 'customerServiceEmail'): string | null;
			
			/**
			* Enable SOM Self Service Plugin
			* @group Ditto - Ditto
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5653) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5996)
			*/
			(name: 'dittoSomSelfServiceEnabled'): boolean | null;
			
			/**
			* Enable MultiShipping

				The attribute is used to enable/disable Multi-Shipment Checkout for each site via BM.
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5660) 
			*/
			(name: 'enableMultiShipping'): boolean | null;
			
			/**
			* Default List Price Book ID
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5668) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5977)
			*/
			(name: 'listPriceDefault'): string | null;
			
			/**
			* Allow Order Cancellation Statuses

				LOM Order statuses where an order will be cancellable
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5676) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6021)
			*/
			(name: 'lom.allowOrderCancellationStatuses'): ReadonlyArray<string> 
			
			/**
			* Allow Order Return Statuses

				LOM Order statuses where an order will be returnable
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5683) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6022)
			*/
			(name: 'lom.allowOrderReturnStatuses'): ReadonlyArray<string> 
			
			/**
			* Auth Token Custom Object Id

				Custom Object used to store/cache SF Auth Tokens.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5690) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6018)
			*/
			(name: 'lom.authTokenCustomObjectId'): string | null;
			
			/**
			* Activate LOM integration

				Flag used to enable or disable integration with Salesforce OMS.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5700) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6017)
			*/
			(name: 'lom.isActive'): boolean | null;
			
			/**
			* Earliest Year for Order Search

				Earliest year used to create date filters in Order History.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5707) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6019)
			*/
			(name: 'lom.ordersearch.earlierYear'): number | null;
			
			/**
			* Order Status Mappings

				Allows the mapping of SF LOM status names into SF CC status names.
			* @group LOM - Lightning Order Management
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5715) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6020)
			*/
			(name: 'lom.statusMappings'): ReadonlyArray<string> 
			
			/**
			* google map api key
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5722) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5980)
			*/
			(name: 'mapAPI'): string | null;
			
			/**
			* Marketing Cloud collect.js URL

				Marketing Cloud collect.js URL. The string MCMID must exist in the URL, for the marketing cloud MID to be inserted into the URL.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5729) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6004)
			*/
			(name: 'mcCollectJsUrl'): string | null;
			
			/**
			* Marketing Cloud Default Mailing Lists

				Default Marketing Cloud mailing lists to assign when customer subscribes. Please provide the numeric "List ID" value.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5739) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6006)
			*/
			(name: 'mcDefaultMailingLists'): ReadonlyArray<number> 
			
			/**
			* Marketing Cloud Enable Analytics

				Select Yes to enable Marketing Cloud Analytics tracking. Requires Member ID to be set.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5746) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6000)
			*/
			(name: 'mcEnableAnalytics'): boolean | null;
			
			/**
			* Marketing Cloud Enable Mailing List Hooks

				Select Yes to enable Marketing Cloud mailing list functionality.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5754) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6005)
			*/
			(name: 'mcEnableMailingLists'): boolean | null;
			
			/**
			* Marketing Cloud Include Tracking Link

				Select Yes to output Marketing Cloud Analytics tracking link into the storefront. Requires Member ID to be set.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5762) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6003)
			*/
			(name: 'mcIncludeTrackingLink'): boolean | null;
			
			/**
			* Marketing Cloud Member ID

				Marketing Cloud Business Unit Member ID aka MID
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5770) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6001)
			*/
			(name: 'mcMID'): string | null;
			
			/**
			* Parent Marketing Cloud Member ID

				Optional parent Marketing Cloud Business Unit Member ID.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5779) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6002)
			*/
			(name: 'mcMIDParent'): string | null;
			
			/**
			* Marketing Cloud Mailing Lists Whitelist

				Whitelist of Marketing Cloud mailing lists. If left empty, all lists are listed for customer. Please provide the numeric "List ID" value.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5788) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6007)
			*/
			(name: 'mcMailingListsWhitelist'): ReadonlyArray<number> 
			
			/**
			* Marketing Cloud Allow Unsubscribing from Lists over Deletion

				This flag will allow the Marketing Cloud cartridge to Unsubscribe users from assigned mailing lists, thus updating the subscriber's status from "Active" to "Unsubscribed".
This will be used in place of fully deleting the record from the list.
			* @group Marketing Cloud - Marketing Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5795) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6008)
			*/
			(name: 'mcUnsubscribeAllowed'): boolean | null;
			
			/**
			* Rate Limiter Threshold

				This number indicates the number of times failures for Logins, GiftCert Balances, and Order Tracking requests will be allowed before displaying a CAPTCHA-style pop-up rate limiter
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5804) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5979)
			*/
			(name: 'rateLimiterThreshold'): number | null;
			
			/**
			* SFRA - Enable Apple Pay

				Enables the Apple Pay plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_applepay must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5813) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5988)
			*/
			(name: 'sfraEnableOverlayApplePay'): boolean | null;
			
			/**
			* SFRA - Enable Data Download

				Enables the Data Download plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_datadownload must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5821) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5985)
			*/
			(name: 'sfraEnableOverlayDataDownload'): boolean | null;
			
			/**
			* SFRA - Enable Gift Registry

				Enables the Gift Registry plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_giftregistry must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5829) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5987)
			*/
			(name: 'sfraEnableOverlayGiftRegistry'): boolean | null;
			
			/**
			* SFRA - Enable In Store Pickup

				Enables the In Store Pickup Plugin in the SFRA Unified Feature Cartridge. Note: The plugin_instorepickup must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5837) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5984)
			*/
			(name: 'sfraEnableOverlayInStorePickup'): boolean | null;
			
			/**
			* SFRA - Enable Product Compare

				Enables the Product Compare plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_productcompare must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5845) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5989)
			*/
			(name: 'sfraEnableOverlayProductCompare'): boolean | null;
			
			/**
			* SFRA - Enable Wishlist

				Enables the Wishlist plugin in the SFRA Unified Feature Cartridge. Note: The cartridge plugin_wishlists must be added to the cartridge path and uploaded to your instance.
			* @group SFRA Unified Feature Cartridge - SFRA Unified Feature Cartridge
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5853) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5986)
			*/
			(name: 'sfraEnableOverlayWishlist'): boolean | null;
			
			/**
			* Shipped Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5861) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6033)
			*/
			(name: 'somStatusCancelledLabel'): string | null;
			
			/**
			* In Progress Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5869) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6031)
			*/
			(name: 'somStatusInProgressLabel'): string | null;
			
			/**
			* Ordered Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5877) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6030)
			*/
			(name: 'somStatusOrderedLabel'): string | null;
			
			/**
			* Returned Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5885) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6034)
			*/
			(name: 'somStatusReturnedLabel'): string | null;
			
			/**
			* Shipped Status Label
			* @group somSelfService - SOM Self Service
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5893) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6032)
			*/
			(name: 'somStatusShippedLabel'): string | null;
			
			/**
			* Is Async Mode Enabled?

				When enabled, synchronization occurs in real-time with the jobs serving as a fallback (jobs then only process failed real-time synchronizations).  Otherwise, all cross-cloud synchronization will be driven by the SCC jobs.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5901) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5968)
			*/
			(name: 'sscIsAsync'): boolean | null;
			
			/**
			* Is Enabled?

				Global enablement flag for the SFCC / SFSC integration; when false, no integration messages are shared with Service Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5909) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5967)
			*/
			(name: 'sscIsEnabled'): boolean | null;
			
			/**
			* Salesforce Connected App Password

				Salesforce Connected App Password
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5917) 
			*/
			(name: 'sscPassword'): string | null;
			
			/**
			* Salesforce Connected App Username

				Salesforce Connected App Username
			* 
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5925) 
			*/
			(name: 'sscUsername'): string | null;
			
			/**
			* Synchronize Cases?

				When enabled, cases created by customers are synchronized with Service Cloud when created / updated in Commerce Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5933) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5971)
			*/
			(name: 'syncCasesEnabled'): boolean | null;
			
			/**
			* Synchronize Customers?

				When enabled, customer profiles are synchronized with Service Cloud when created / updated in Commerce Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5941) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5969)
			*/
			(name: 'syncCustomersEnabled'): boolean | null;
			
			/**
			* Synchronize Orders?

				When enabled, orders placed by customers are synchronized with Service Cloud when created / updated in Commerce Cloud.
			* @group ServiceCloudConnector - Service Cloud Connector
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5949) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5970)
			*/
			(name: 'syncOrdersEnabled'): boolean | null;
			
			/**
			* Test Preference For demo 2
			* @group TestDemoPrefs - Test Demo Prefs
			* @source [attribute](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#5957) | [group](file:/Users/clavery/code/b2c-tools-demo/tmp/20220421T194306457Z_export/meta/system-objecttype-extensions.xml#6026)
			*/
			(name: 'testPreferenceForDemo2'): string | null;
			
	}
}