name: Publish Package
on:
  release:
    types: [ released ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Bump Versions in Workflows
        shell: bash
        run: |
          git config user.email "clavery@salesforce.com"
          git config user.name "Github Actions"
          git checkout main
          NUMBERED_VERSION=$(echo "${{ github.event.release.tag_name }}" | cut -d'v' -f 2)
          perl -0777 -i.original -pe 's/"version"\s*:\s*"[0-9\.]+"/"version": "'"${NUMBERED_VERSION}"'"/igs' package.json
          git add package.json
          git commit -m "bumping version on release of ${NUMBERED_VERSION}"
          git push

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
